paramFile: <path of param file>

config:
  - process_name: CCMS~HK~CCMS_HK_CPS102~C_ACCT~1
    ctl_id: 20020
    group_id: 2
    country_code: HK
    source_system_name: CCM
    tQuery: <path of the sql>
    process_type: master
    rejection_threshold: 100
    run_order: 6
    source:
        sourceTableName: XYZ
        sourceSchemaName: <some schema if the dataset is File>
        columnDelimiter: <if source is a HDFS>
    target:
        targetTableName: <Name of the target table>
        targetTableSchema: <File path of the target schema>
        targetKeyColumn: emp_id
    validationRules:
      - validationGranualityLevel: table
        isRuleActive: true
        totalCountGte: 100
        errorLevel: error
        filterCondition: [process_date='2017-04-05',source_country_code='HK']
      - validationGranualityLevel: column
        columnName: emp_id
        isRuleActive: true
        completeness: 99
      - validationGranualityLevel: column
        columnName: emp_id
        isRuleActive: true
        uniqueness: 100

